# Your workflow name.
name: Deploy to Vercel.

# Run workflow on every push to main branch.
on:
  push:
    branches: [master]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Vercel. # Your custom step name
        uses: vercel/vercel-action # GitHub action name (leave it as it is).
        with:
          # Below you must provide variables for your Vercel app.

          # The email address associated with your Vercel account.
          # If you don't want to use repository secrets (which is recommended) you can do:
          # email: my.email@example.com
          email: ${{ secrets.VERCEL_EMAIL }}

          # Vercel API key associated with provided user's email.
          # Api Key is available under your Vercel account settings.
          vercel_api_key: ${{ secrets.VERCEL_API_KEY }}

          # Name of the Vercel application to which the build is to be sent.
          vercel_app_name: ${{ secrets.Vercel_APP_NAME }}

          # (Optional, default: "./")
          # Dockerfile directory.
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./

          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile

          # (Optional, default: "")
          # Additional options of docker build command.
          docker_options: "--no-cache"
          
          process_type: web
### ⬆ IMPORTANT PART ⬆ ###
